sonar.projectKey=program_fitzone
sonar.projectName=program_fitzone
sonar.sourceEncoding=UTF-8

sonar.sources=backend/fit_zone_program,frontend/frontend
sonar.tests=tests,test_program.py
sonar.test.inclusions=tests/**/*.py,tests/*.py,test_program.py

sonar.python.coverage.reportPaths=coverage.xml

sonar.exclusions=**/__pycache__/**,**/*.pyc,**/*.sqlite3,backend/fit_zone_program/data/**,frontend/frontend/assets/**,.scannerwork/**
