sonar.projectKey=program_fitzone
sonar.projectName=program_fitzone
sonar.host.url=http://localhost:9000

sonar.sources=src/models,src/services
sonar.tests=tests
sonar.test.inclusions=tests/**/*.py
sonar.python.coverage.reportPaths=coverage.xml

sonar.exclusions=**/__pycache__/**,data/**,z/**,.pytest_cache/**
